version: '3'
services:

  #App
  demix-app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    image: nesatfit/demix-app:1.0
    container_name: demix-app
#    command: ./refresh.sh
    volumes:
      - ./demixer/.env:/var/www/.env
      - web_data:/var/www
  #Webserver
  demix-nginx:
#    build:
#      context: ./
#      dockerfile: web.dockerfile
    image: nginx:alpine-perl
    container_name: demix-nginx
    working_dir: /var/www
    volumes:
      - web_data:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HTTP_PORT}:80

networks:
  default:
    external:
      name: ${NETWORK}

volumes:
  web_data: